action_modes = ["activate action mode", "activate action", "action mode", "activity action mode", "activity action mod", "action mod", "action", "activity action"]
face_modes = ["activate face mode", "activate safe mode", "safe mode", "face mode", "safe", "face"]
emotion_modes = ["activate emotion mode", "activate motion mode", "activity motion mode", "activity motion mod", "motion mode", "emotion mode", "emotion mod", "emotion", "activity motion", "activate motion"]
chat_modes = ["activate chat mode", "chat mode", "activate chat", "activity chat mode", "activity chat", "chat mod"]
additional = ["Sorry I didnt understand what you are saying", "Try rephrasing that", "which mode do you want to activate", "I am having trouble hearing  you"]